import Head from "next/head";
// import { Inter } from "@next/font/google";
import Main from "@components/Main";
import * as React from "react";
import Textarea from "react-dropzone-textarea";
import LangSelect from "@components/LangSelect";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [data, setData] = React.useState("");
	const [outLang, setOutLang] = React.useState<string>("en-US");

	React.useEffect(() => {
		const lsText = localStorage.getItem("text");
		if (lsText) setData(lsText);
		const lsLang = localStorage.getItem("outLang");
		setOutLang(lsLang ?? "en-US");
	}, []);
	// const input = React.createRef<HTMLTextAreaElement>();
	// const forwardInput = () => {
	// 	const el = input.current;
	// 	console.log("forward")
	// 	if (el?.value) {
	// 		setData(el.value);
	// 	}
	// };
	const forwardInput = (text: string) => {
		localStorage.setItem("text", text);
		setData(text);
	};
	// React.useEffect(() => {
	// 	if (input.current) {
	// 		input.current.focus();
	// 	}
	// }, [input]);

	return (
		<>
			<Head>
				<title>Read Translate</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<h1>Read Translate</h1>
				<span style={{ display: "flex" }}>
					<Textarea
						// ref={input}
						value={data}
						onChange={(e: any) => forwardInput(e.target.value)}
						onDropRead={(text: string) => forwardInput(text)}
						style={{ width: "400px" }}
						textareaProps={{
							placeholder: "Write, Paste or drop a .txt here",
						}}
					/>
					<span>
						<h4>Output Language:</h4>
						<LangSelect
							name="output-language"
							onChange={(item) => {
								setOutLang(item.target.value);
								localStorage.setItem(
									"outLang",
									item.target.value
								);
							}}
							value={outLang}
						/>
					</span>
				</span>
			</header>
			<Main data={data} outLang={outLang} />
		</>
	);
}
