import Head from "next/head";
// import { Inter } from "@next/font/google";
import Main from "@components/Main";
import * as React from "react";
import Textarea from "react-dropzone-textarea";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [data, setData] = React.useState("");
	const input = React.createRef<HTMLTextAreaElement>();
	// const forwardInput = () => {
	// 	const el = input.current;
	// 	console.log("forward")
	// 	if (el?.value) {
	// 		setData(el.value);
	// 	}
	// };
	const forwardInput = (text: string) => {
		setData(text);
	};
	React.useEffect(() => {
		if (input.current) {
			input.current.focus();
		}
	}, [input]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<h1>Read Translate</h1>
				<span>
					<Textarea
						ref={input}
						value={data}
						onChange={(e: any) => forwardInput(e.target.value)}
						onDropRead={(text: string) => forwardInput(text)}
						style={{ width: "400px" }}
						textareaProps={{
							placeholder: "Write, Paste or drop a .txt here",
						}}
					/>
				</span>
			</header>
			<Main data={data} />
		</>
	);
}
