import Head from "next/head";
// import { Inter } from "@next/font/google";
import Main from "@components/Main";
import * as React from "react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [data, setData] = React.useState("");
	const input = React.createRef<HTMLTextAreaElement>();
	const forwardInput = () => {
		const el = input.current;
		if (el?.value) {
			setData(el.value);
		}
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<h1>Read Translate</h1>
				<span>
					<textarea ref={input} />
					<input type="button" value="Paste" onClick={forwardInput} />
				</span>
			</header>
			<Main data={data} />
		</>
	);
}
